# Generated by Django 4.0.5 on 2022-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='baterai',
            field=models.ManyToManyField(to='ahp.baterai'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.ManyToManyField(to='ahp.brand'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='harga',
            field=models.ManyToManyField(to='ahp.harga'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='kamera',
            field=models.ManyToManyField(to='ahp.kamera'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='memory',
            field=models.ManyToManyField(to='ahp.memory'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='os',
            field=models.ManyToManyField(to='ahp.os'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='penggunaan',
            field=models.ManyToManyField(to='ahp.penggunaan'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.ManyToManyField(to='ahp.ram'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ukuran_layar',
            field=models.ManyToManyField(to='ahp.ukuranlayar'),
        ),
    ]
