# Generated by Django 4.0.5 on 2022-09-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0002_smartphone_baterai_smartphone_brand_smartphone_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baterai',
            name='kapasistas_baterai',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='baterai',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='baterai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.baterai'),
        ),
    ]
