# Generated by Django 4.0.5 on 2022-09-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0003_alter_baterai_kapasistas_baterai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='brand',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.brand'),
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='kamera',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='kamera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.kamera'),
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='os',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.os'),
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='ukuran_layar',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ukuran_layar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.ukuranlayar'),
        ),
    ]
