# Generated by Django 4.0.5 on 2022-09-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0007_rename_kapasitas_baterai_baterai_kapasistas_baterai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baterai',
            old_name='kapasistas_baterai',
            new_name='kapasitas_baterai',
        ),
    ]
