# Generated by Django 4.0.5 on 2022-09-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0008_rename_kapasistas_baterai_baterai_kapasitas_baterai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baterai',
            old_name='kapasitas_baterai',
            new_name='kapasistas_baterai',
        ),
    ]
