# Generated by Django 4.0.5 on 2022-09-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0009_rename_kapasitas_baterai_baterai_kapasistas_baterai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='ram',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahp.ram'),
        ),
    ]
