# Generated by Django 4.0.5 on 2022-09-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0010_remove_smartphone_ram_smartphone_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='memory',
        ),
    ]
